### PR TITLE
Bibtex importing bugfix

### PR DESCRIPTION
**Pull request by Matherion**
Minor bugfix to allow importing BibTeX files with comments, as created by e.g. JabRef.

### CODE REVIEW

**Comment by Matherion** [comment]
Hey @mjwestgate! I was wondering whether you were thinking of merging this.

Because I'm going to submit another one I think, a bug in importing .RIS files :-) But if these aren't integrated, PRs may not be the best route?

**Comment by Matherion** [comment]
Oh, wait, re-read out Twitter message history now - revtools shouldn't be used for importing any more. An indeed, "synthesisr" doesn't have the bug. Closing this PR!

**Comment by danielvartan** [comment]
> revtools shouldn't be used for importing any more.

Is that true? Can you link the twitter message you mentioned?

**Comment by Matherion** [comment]
It was a DM - but the idea is that the importing functionality is now in [synthesisr](https://github.com/rmetaverse/synthesisr).

**Pull request closed without merging**
